"""advisory_tasks queue + queue_depth_samples

Revision ID: 9dc180fddf7e
Revises: bf226f7100f5
Create Date: 2026-07-20 11:47:37.280017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc180fddf7e'
down_revision: Union[str, Sequence[str], None] = 'bf226f7100f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_depth_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued', sa.Integer(), nullable=False),
    sa.Column('running', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_depth_samples_time', 'queue_depth_samples', ['sampled_at'], unique=False)
    op.create_table('advisory_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.Text(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('advisory_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='ck_advisory_tasks_status'),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'run_date', name='uq_advisory_tasks_idempotency')
    )
    op.create_index('ix_advisory_tasks_claim', 'advisory_tasks', ['run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_advisory_tasks_claim', table_name='advisory_tasks', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('advisory_tasks')
    op.drop_index('ix_queue_depth_samples_time', table_name='queue_depth_samples')
    op.drop_table('queue_depth_samples')
    # ### end Alembic commands ###
