"""initial schema: five core tables plus feature cache

Revision ID: bf226f7100f5
Revises: 
Create Date: 2026-07-20 10:57:15.331818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf226f7100f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.Text(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('irrigation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spray', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reconciliation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('irrigation_confidence', sa.Float(), nullable=True),
    sa.Column('spray_confidence', sa.Float(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('prompt_name', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('prompt_source', sa.Text(), nullable=True),
    sa.Column('model_id', sa.Text(), nullable=True),
    sa.Column('deps_hash', sa.Text(), nullable=False),
    sa.Column('code_sha', sa.Text(), nullable=True),
    sa.Column('dataset_version', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('degraded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pre_correction_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'run_date', name='uq_advisories_idempotency')
    )
    op.create_index('ix_advisories_history', 'advisories', ['tenant', 'run_date'], unique=False)
    op.create_index(op.f('ix_advisories_trace_id'), 'advisories', ['trace_id'], unique=False)
    op.create_table('feature_cache',
    sa.Column('tenant', sa.Text(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('deps_hash', sa.Text(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant', 'run_date', 'deps_hash')
    )
    op.create_table('grower_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('crop', sa.Text(), nullable=False),
    sa.Column('irrigation_method', sa.Text(), nullable=False),
    sa.Column('spray_sensitivity', sa.Text(), nullable=False),
    sa.Column('kc', sa.Float(), nullable=False),
    sa.Column('root_depth_m', sa.Float(), nullable=False),
    sa.Column('taw_mm', sa.Float(), nullable=False),
    sa.Column('mad_fraction', sa.Float(), nullable=False),
    sa.Column('initial_depletion_mm', sa.Float(), nullable=False),
    sa.Column('effective_rain_fraction', sa.Float(), nullable=False),
    sa.Column('rain_skip_mm', sa.Float(), nullable=False),
    sa.Column('refill_fraction', sa.Float(), nullable=False),
    sa.Column('deltat_ideal_low', sa.Float(), nullable=False),
    sa.Column('deltat_ideal_high', sa.Float(), nullable=False),
    sa.Column('deltat_inversion_below', sa.Float(), nullable=False),
    sa.Column('deltat_marginal_upper', sa.Float(), nullable=False),
    sa.Column('wind_ideal_low_ms', sa.Float(), nullable=False),
    sa.Column('wind_ideal_high_ms', sa.Float(), nullable=False),
    sa.Column('spray_index_cutoff', sa.Float(), nullable=False),
    sa.Column('spray_index_higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('rain_fast_hours', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deps_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'location', 'valid_from', name='uq_grower_config_version')
    )
    op.create_index('ix_grower_config_current', 'grower_config', ['tenant', 'location', 'valid_to'], unique=False)
    op.create_index(op.f('ix_grower_config_deps_hash'), 'grower_config', ['deps_hash'], unique=False)
    op.create_index('uq_grower_config_open', 'grower_config', ['tenant', 'location'], unique=True, postgresql_where=sa.text('valid_to IS NULL'))
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_ms', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('spray_index', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.Column('dew_point_c', sa.Float(), nullable=True),
    sa.Column('vpd_kpa', sa.Float(), nullable=True),
    sa.Column('delta_t_c', sa.Float(), nullable=True),
    sa.Column('wind_dir_deg', sa.Float(), nullable=True),
    sa.Column('ghi_wm2', sa.Float(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('history', 'forecast')", name='ck_weather_observations_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'location', 'observed_at', 'kind', 'source', name='uq_weather_observations_natural')
    )
    op.create_index('ix_weather_observations_lookup', 'weather_observations', ['tenant', 'location', 'kind', 'observed_at'], unique=False)
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advisory_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_role', sa.Enum('agronomist', 'farmer', name='reviewer_role'), nullable=False),
    sa.Column('reviewer_id', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=False),
    sa.Column('leg', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('promoted_to_golden', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("leg IS NULL OR leg IN ('irrigation', 'spray', 'reconciliation')", name='ck_annotations_leg'),
    sa.CheckConstraint("verdict IN ('agree', 'disagree', 'unclear')", name='ck_annotations_verdict'),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_annotations_advisory', 'annotations', ['advisory_id'], unique=False)
    op.create_index('ix_annotations_golden', 'annotations', ['promoted_to_golden'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('deps_hash', sa.Text(), nullable=False),
    sa.Column('code_sha', sa.Text(), nullable=False),
    sa.Column('dataset_version', sa.Text(), nullable=False),
    sa.Column('evaluator', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('recall_should_irrigate', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('advisory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advisory_id'], ['advisories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_advisory_id'), 'eval_runs', ['advisory_id'], unique=False)
    op.create_index('ix_eval_runs_drift', 'eval_runs', ['prompt_version', 'model_id', 'dataset_version', 'code_sha'], unique=False)
    op.create_index('ix_eval_runs_evaluator', 'eval_runs', ['evaluator', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eval_runs_evaluator', table_name='eval_runs')
    op.drop_index('ix_eval_runs_drift', table_name='eval_runs')
    op.drop_index(op.f('ix_eval_runs_advisory_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index('ix_annotations_golden', table_name='annotations')
    op.drop_index('ix_annotations_advisory', table_name='annotations')
    op.drop_table('annotations')
    op.drop_index('ix_weather_observations_lookup', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('uq_grower_config_open', table_name='grower_config', postgresql_where=sa.text('valid_to IS NULL'))
    op.drop_index(op.f('ix_grower_config_deps_hash'), table_name='grower_config')
    op.drop_index('ix_grower_config_current', table_name='grower_config')
    op.drop_table('grower_config')
    op.drop_table('feature_cache')
    op.drop_index(op.f('ix_advisories_trace_id'), table_name='advisories')
    op.drop_index('ix_advisories_history', table_name='advisories')
    op.drop_table('advisories')
    # ### end Alembic commands ###
